[versions]
# stage runner version
stage-runner = '0.3.5-SNAPSHOT'

byte-buddy = '[1.15,1.19)'
jetbrains-annotations = '[26.0,26.2)'
junit = '6.1.+'
lombok =  '[1.18,1.19)'
spring = '[5.3,7.0)'

[libraries]
byte-buddy = { module = 'net.bytebuddy:byte-buddy', version.ref = 'byte-buddy' }
jetbrains-annotations = { module = 'org.jetbrains:annotations', version.ref = 'jetbrains-annotations' }
junit-jupiter = { module = 'org.junit.jupiter:junit-jupiter', version.ref = 'junit' }
lombok = { module = 'org.projectlombok:lombok', version.ref = 'lombok' }
spring-context = { module = 'org.springframework:spring-context', version.ref = 'spring' }
spring-test = { module = 'org.springframework:spring-test', version.ref = 'spring' }

[plugins]
publish-on-central = { id = 'org.danilopianini.publish-on-central', version = '9.2.10' }
test-logger = { id = 'com.adarshr.test-logger', version = '4.0.0' }
